-- ============================================================
-- 迁移脚本：将 games.id 从 GENERATED ALWAYS 改为 GENERATED BY DEFAULT
-- 
-- 背景：
--   旧版 schema 使用 GENERATED ALWAYS AS IDENTITY，禁止显式插入 id，
--   导致 localize-games.mjs 生成的 COPY 带 id 语句在首次部署时失败。
--   新版 schema 改为 GENERATED BY DEFAULT AS IDENTITY，允许 COPY/INSERT 带显式 id，
--   同时保留序列自增能力（webhook 新游戏仍可用序列分配 id）。
--
-- 适用场景：
--   已有部署（远端 DB 已用旧版 schema 初始化）需要在线迁移，不丢失数据。
--   新部署无需执行此脚本（01-schema.sql 已使用 BY DEFAULT）。
--
-- 使用方式：
--   docker compose -f deploy/docker-compose.yml exec -T postgres \
--     psql -U nesbox -d nesbox < deploy/scripts/migrate-identity.sql
--
-- 验证：
--   SELECT column_name, is_identity, identity_generation 
--   FROM information_schema.columns 
--   WHERE table_name = 'games' AND column_name = 'id';
--   期望结果：is_identity=YES, identity_generation=d (BY DEFAULT)
-- ============================================================

BEGIN;

-- 将 games.id 从 GENERATED ALWAYS 改为 GENERATED BY DEFAULT
-- 此操作在线执行，不锁表，不丢失数据
ALTER TABLE public.games ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 同步序列值到当前最大 id（确保后续 INSERT 不冲突）
-- 如果序列已经正确（localize-games.mjs 的 setval 已执行），此操作无害
SELECT pg_catalog.setval(
  'public.games_id_seq',
  GREATEST(
    pg_catalog.last_value,
    (SELECT COALESCE(MAX(id), 0) FROM public.games)
  ),
  true
);

COMMIT;

-- 验证输出
DO $$
DECLARE
  v_seq_val bigint;
  v_max_id  integer;
BEGIN
  SELECT last_value INTO v_seq_val FROM public.games_id_seq;
  SELECT COALESCE(MAX(id), 0) INTO v_max_id FROM public.games;
  RAISE NOTICE '迁移完成：games.id 已改为 GENERATED BY DEFAULT AS IDENTITY';
  RAISE NOTICE '当前序列值：%', v_seq_val;
  RAISE NOTICE '当前最大 id：%', v_max_id;
END $$;
